### ISSUE TITLE
productionの時/assets/user_default.pngにアクセス出来ない

### ISSUE THREAD

**Issue by abcang** [asakura-dev/Gruppi-Goods#11]

**Comment by asakura-dev** [comment]
どこからもアクセス出来ない感じ？ビューのヘッダーでuser_default.pngを参照するときも表示されない？

**Comment by abcang** [comment]
productionの時はasset compileされたものが使われるから、`/assets/user_default.png`だとアクセス出来ないみたい。
もう直したのでプルリク投げます
